@startuml

class Person{
    -name: String
    -email: String
    +getName(): String 
    +getEmailAddress(): String 
}

class Lecturer{
    -lecturerID: int 
    -taughtCourses: ArrayList<Course>
    +getTaughtCourses(): ArrayList<Course>
    +getLecturerID(): int 
}

class Course{
    -courseID: int 
    -students: ArrayList<Student>
    -taughtBy: Lecturer

    +getCourseID(): int 
    +getTeacher(): Lecturer
    +addStudent(Student student)
    +removeStudent(int studentID)
    +assignTeacher(Lecturer lecturer)
    +getListStudents(): ArrayList<Student>
   
    
}

class Student{
    -ID: int 
    -courses: ArrayList<Course>
    +addCourse(Course course)
    +getStudentID(): int 
    
}


Lecturer "1" *-- "n" Course : taughtBy
Student "0" o-- "n"  Course : AttendedBy
Lecturer --|> Person
Student --|> Person 


@enduml