# Project1


@startuml

class Vehicle {
 -color: String
 -speed: int

 +turnLeft(int angle)
 +turnRight(int angle)
  
}


class Bicycle{
-numberOfWheels: int
-ringBell: Object 
}

class MotorVehicle{
- sizeOfEngine: int
- licensePlate: int

+ getSizeOfEngine(): int
+ setSizeOfEngine(int sizeOfEngine)
+ getLicensePlate(): int
+ setLicensePlate(int licensePlate)

}

class MotorBike{
- manufacturer: String
- isTwoSeater: Boolean
- engineType : String

+ getManufacturer(): String
+ setManufacturer(String manufacturer)
+ setEngineType(String engineType)
+ getEngineType(): String
}

class Car{
- fuelType: String
- numDoors: int
- yearManufacturing: int

+ setFuelType(String fuelType)
+ getFuelType(): String
+ setNumDoors(int numDoors)
+ getNumDoors(): int
+ setYearManufacturing(int yearManufacturing)
+ getYearManufacturing(): int
}

MotorVehicle --|> Vehicle 

Bicycle  --|> Vehicle 

MotorBike --|> MotorVehicle 

Car --|> MotorVehicle


@enduml
